# Generated by Django 5.1.6 on 2026-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
