# Generated by Django 5.1.6 on 2026-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_importrun_attempts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['source', 'is_remote', '-salary_max'], name='idx_vacancy_source_remote_sal'),
        ),
    ]
